syntax = "proto3";

package anticheat;

option java_multiple_files = true;

import "generic.proto";

message NodeRegistration {
  message Register {
    int32 NodeVersion = 1;
    string SharedKey = 2;
    NodeResources resources = 3;
  }
  message Response {
    bool Succeeded = 1;
  }
}

message NodeResources {
  uint32 memory = 1;
  uint32 cpu = 2;
}

//message AnticheatMessage {
//  uint32 messageId = 1;
//  uint32 messageSize = 2;
//  bytes message = 3;
//}

message DisconnectNode {
  generic.DisconnectReason Reason = 1;
}

message NodeProxyNegotiation {
  uint32 Port = 1;
  string ClientKey = 2;
}