syntax = "proto3";

package server;

option java_multiple_files = true;

import "generic.proto";

message ServerRegistration {
  message Register {
    int32 PluginVersion = 1;
    generic.ServerInfo ServerInfo = 2;
  }

  message Response {
    bool Succeeded = 1;
    optional string UuidKey = 2;
  }
}

message DisconnectServer {
  optional string UuidKey = 1;
  generic.DisconnectReason Reason = 2;
}

message Ready {}

message ProxyMessage {
  uint32 MessageID = 1;
  // Message data is encoding with utf-8
  string MessageData = 2;
}